spring.application.name=calendar
# H2 Konsolunu aktif et (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Veritabanı bağlantı ayarları
spring.datasource.url=jdbc:h2:mem:calendardb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate (JPA) ayarları - tabloları otomatik oluşturur
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true